title: cc
default_lang: fr
author:
  name: cc
  email: chris.coutures@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
